/*
 * Powell Makerspace Login Application API
 * Application designed to track and analyze visit and member information.
 *
 * OpenAPI spec version: 1.0
 * Contact: r.anthony1961@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
